# Generated by Django 4.0 on 2022-04-26 13:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=150)),
                ('port', models.IntegerField(default=465)),
                ('login', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('email_from', models.CharField(max_length=150)),
                ('use_ssl', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=80)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to', models.JSONField(default=list)),
                ('cc', models.JSONField(default=list)),
                ('bcc', models.JSONField(default=list)),
                ('sent_date', models.DateField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BASE.mailbox')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BASE.template')),
            ],
        ),
    ]
