# Generated by Django 4.0 on 2022-04-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='text',
            field=models.TextField(default='test', max_length=450),
            preserve_default=False,
        ),
    ]
