# Generated by Django 4.0 on 2022-05-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0002_template_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='attachment',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
